// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WonjinApi.Data;

#nullable disable

namespace WonjinApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260827104034_AddInfluencerLinks")]
    partial class AddInfluencerLinks
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("wonjin")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WonjinApi.Models.AuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("action");

                    b.Property<string>("ActorEmail")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("actor_email");

                    b.Property<string>("ActorRole")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("actor_role");

                    b.Property<int?>("ActorUserId")
                        .HasColumnType("integer")
                        .HasColumnName("actor_user_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("EntityId")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("entity_type");

                    b.Property<string>("Ip")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("ip");

                    b.Property<int>("StatusCode")
                        .HasColumnType("integer")
                        .HasColumnName("status_code");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("summary");

                    b.HasKey("Id")
                        .HasName("pk_audit_logs");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_audit_logs_created_at");

                    b.HasIndex("ActorUserId", "CreatedAt")
                        .HasDatabaseName("ix_audit_logs_actor_user_id_created_at");

                    b.HasIndex("EntityType", "CreatedAt")
                        .HasDatabaseName("ix_audit_logs_entity_type_created_at");

                    b.ToTable("audit_logs", "wonjin");
                });

            modelBuilder.Entity("WonjinApi.Models.Consultant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("name");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("sort_order");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_consultants");

                    b.HasIndex("IsActive", "SortOrder")
                        .HasDatabaseName("ix_consultants_is_active_sort_order");

                    b.ToTable("consultants", "wonjin");
                });

            modelBuilder.Entity("WonjinApi.Models.InfluencerLink", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("display_name");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Locale")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasDefaultValue("zh-CN")
                        .HasColumnName("locale");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UtmCampaign")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasDefaultValue("")
                        .HasColumnName("utm_campaign");

                    b.Property<string>("UtmMedium")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasDefaultValue("influencer")
                        .HasColumnName("utm_medium");

                    b.Property<string>("UtmSource")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasDefaultValue("")
                        .HasColumnName("utm_source");

                    b.HasKey("Id")
                        .HasName("pk_influencer_links");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ux_influencer_links_code");

                    b.HasIndex("IsActive", "CreatedAt")
                        .HasDatabaseName("ix_influencer_links_is_active_created_at");

                    b.ToTable("influencer_links", "wonjin", t =>
                        {
                            t.HasCheckConstraint("ck_influencer_links_locale", "locale IN ('zh-CN','zh-TW','en','ko')");
                        });
                });

            modelBuilder.Entity("WonjinApi.Models.LandingDailyStat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ReferralCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("")
                        .HasColumnName("referral_code");

                    b.Property<DateOnly>("StatDate")
                        .HasColumnType("date")
                        .HasColumnName("stat_date");

                    b.Property<string>("UtmCampaign")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasDefaultValue("")
                        .HasColumnName("utm_campaign");

                    b.Property<string>("UtmMedium")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasDefaultValue("")
                        .HasColumnName("utm_medium");

                    b.Property<string>("UtmSource")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasDefaultValue("")
                        .HasColumnName("utm_source");

                    b.Property<int>("VisitCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("visit_count");

                    b.HasKey("Id")
                        .HasName("pk_landing_daily_stats");

                    b.HasIndex("StatDate")
                        .HasDatabaseName("ix_landing_daily_stats_stat_date");

                    b.HasIndex("StatDate", "ReferralCode", "UtmSource", "UtmMedium", "UtmCampaign")
                        .IsUnique()
                        .HasDatabaseName("ux_landing_daily_stats_key");

                    b.ToTable("landing_daily_stats", "wonjin");
                });

            modelBuilder.Entity("WonjinApi.Models.Procedure", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name_en");

                    b.Property<string>("NameKo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name_ko");

                    b.Property<string>("NameZhCn")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name_zh_cn");

                    b.Property<string>("NameZhTw")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name_zh_tw");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("sort_order");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_procedures");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ux_procedures_code");

                    b.HasIndex("IsActive", "SortOrder")
                        .HasDatabaseName("ix_procedures_is_active_sort_order");

                    b.ToTable("procedures", "wonjin");
                });

            modelBuilder.Entity("WonjinApi.Models.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<bool>("IsRevoked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_revoked");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("token_hash");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_refresh_tokens");

                    b.HasIndex("TokenHash")
                        .HasDatabaseName("ix_refresh_tokens_token_hash");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_refresh_tokens_user_id");

                    b.ToTable("refresh_tokens", "wonjin");
                });

            modelBuilder.Entity("WonjinApi.Models.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date")
                        .HasColumnName("birth_date");

                    b.Property<string>("CancelReason")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("cancel_reason");

                    b.Property<DateTimeOffset?>("CancelledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cancelled_at");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset?>("ConfirmedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("confirmed_at");

                    b.Property<int?>("ConsultantId")
                        .HasColumnType("integer")
                        .HasColumnName("consultant_id");

                    b.Property<DateTimeOffset?>("ConsultingAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("consulting_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<int?>("DeletedByUserId")
                        .HasColumnType("integer")
                        .HasColumnName("deleted_by_user_id");

                    b.Property<decimal?>("DepositAmount")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("deposit_amount");

                    b.Property<string>("DepositCurrency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasDefaultValue("CNY")
                        .HasColumnName("deposit_currency");

                    b.Property<bool>("DepositPaid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("deposit_paid");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("gender");

                    b.Property<string>("Locale")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("locale");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<TimeOnly>("PreferredContactTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("preferred_contact_time");

                    b.Property<string>("ReferralCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("")
                        .HasColumnName("referral_code");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("New")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UtmCampaign")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasDefaultValue("")
                        .HasColumnName("utm_campaign");

                    b.Property<string>("UtmMedium")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasDefaultValue("")
                        .HasColumnName("utm_medium");

                    b.Property<string>("UtmSource")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasDefaultValue("")
                        .HasColumnName("utm_source");

                    b.Property<DateOnly?>("VisitDate")
                        .HasColumnType("date")
                        .HasColumnName("visit_date");

                    b.Property<TimeOnly?>("VisitTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("visit_time");

                    b.Property<DateTimeOffset?>("VisitedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("visited_at");

                    b.Property<string>("WechatId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("wechat_id");

                    b.HasKey("Id")
                        .HasName("pk_reservations");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ux_reservations_code");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_reservations_created_at");

                    b.HasIndex("DeletedByUserId")
                        .HasDatabaseName("ix_reservations_deleted_by_user_id");

                    b.HasIndex("VisitDate")
                        .HasDatabaseName("ix_reservations_visit_date")
                        .HasFilter("status IN ('Confirmed','Visited')");

                    b.HasIndex("ConsultantId", "Status")
                        .HasDatabaseName("ix_reservations_consultant_id_status");

                    b.HasIndex("Status", "CreatedAt")
                        .HasDatabaseName("ix_reservations_status_created_at");

                    b.ToTable("reservations", "wonjin", t =>
                        {
                            t.HasCheckConstraint("ck_reservations_deposit_amount", "deposit_amount >= 0");

                            t.HasCheckConstraint("ck_reservations_deposit_currency", "deposit_currency IN ('CNY','KRW')");

                            t.HasCheckConstraint("ck_reservations_gender", "gender IN ('Female','Male','Other')");

                            t.HasCheckConstraint("ck_reservations_status", "status IN ('New','Consulting','Confirmed','Visited','Cancelled')");
                        });
                });

            modelBuilder.Entity("WonjinApi.Models.ReservationCodeCounter", b =>
                {
                    b.Property<DateOnly>("CodeDate")
                        .HasColumnType("date")
                        .HasColumnName("code_date");

                    b.Property<int>("LastSeq")
                        .HasColumnType("integer")
                        .HasColumnName("last_seq");

                    b.HasKey("CodeDate")
                        .HasName("pk_reservation_code_counters");

                    b.ToTable("reservation_code_counters", "wonjin");
                });

            modelBuilder.Entity("WonjinApi.Models.ReservationLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("action");

                    b.Property<string>("ActorName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("actor_name");

                    b.Property<int?>("ActorUserId")
                        .HasColumnType("integer")
                        .HasColumnName("actor_user_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Note")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("note");

                    b.Property<int>("ReservationId")
                        .HasColumnType("integer")
                        .HasColumnName("reservation_id");

                    b.HasKey("Id")
                        .HasName("pk_reservation_logs");

                    b.HasIndex("ReservationId", "CreatedAt")
                        .HasDatabaseName("ix_reservation_logs_reservation_id_created_at");

                    b.ToTable("reservation_logs", "wonjin");
                });

            modelBuilder.Entity("WonjinApi.Models.ReservationNote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AuthorName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("author_name");

                    b.Property<int?>("AuthorUserId")
                        .HasColumnType("integer")
                        .HasColumnName("author_user_id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("body");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("ReservationId")
                        .HasColumnType("integer")
                        .HasColumnName("reservation_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_reservation_notes");

                    b.HasIndex("AuthorUserId")
                        .HasDatabaseName("ix_reservation_notes_author_user_id");

                    b.HasIndex("ReservationId", "CreatedAt")
                        .HasDatabaseName("ix_reservation_notes_reservation_id_created_at");

                    b.ToTable("reservation_notes", "wonjin");
                });

            modelBuilder.Entity("WonjinApi.Models.ReservationNoteRevision", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("body");

                    b.Property<DateTimeOffset>("EditedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("edited_at");

                    b.Property<string>("EditedByName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("edited_by_name");

                    b.Property<int?>("EditedByUserId")
                        .HasColumnType("integer")
                        .HasColumnName("edited_by_user_id");

                    b.Property<int>("ReservationNoteId")
                        .HasColumnType("integer")
                        .HasColumnName("reservation_note_id");

                    b.HasKey("Id")
                        .HasName("pk_reservation_note_revisions");

                    b.HasIndex("EditedByUserId")
                        .HasDatabaseName("ix_reservation_note_revisions_edited_by_user_id");

                    b.HasIndex("ReservationNoteId", "EditedAt")
                        .HasDatabaseName("ix_reservation_note_revisions_note_id_edited_at");

                    b.ToTable("reservation_note_revisions", "wonjin");
                });

            modelBuilder.Entity("WonjinApi.Models.ReservationProcedure", b =>
                {
                    b.Property<int>("ReservationId")
                        .HasColumnType("integer")
                        .HasColumnName("reservation_id");

                    b.Property<int>("ProcedureId")
                        .HasColumnType("integer")
                        .HasColumnName("procedure_id");

                    b.HasKey("ReservationId", "ProcedureId")
                        .HasName("pk_reservation_procedures");

                    b.HasIndex("ProcedureId")
                        .HasDatabaseName("ix_reservation_procedures_procedure_id");

                    b.ToTable("reservation_procedures", "wonjin");
                });

            modelBuilder.Entity("WonjinApi.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("email");

                    b.Property<bool>("IsSuspended")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_suspended");

                    b.Property<string>("Locale")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasDefaultValue("ko")
                        .HasColumnName("locale");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("role");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ux_users_email");

                    b.HasIndex("Role")
                        .HasDatabaseName("ix_users_role");

                    b.ToTable("users", "wonjin", t =>
                        {
                            t.HasCheckConstraint("ck_users_locale", "locale IN ('zh-CN','zh-TW','en','ko')");

                            t.HasCheckConstraint("ck_users_role", "role IN ('Admin','HospitalManager','Consultant')");
                        });
                });

            modelBuilder.Entity("WonjinApi.Models.WebPushSubscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Auth")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("auth");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("endpoint");

                    b.Property<string>("P256dh")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("p256dh");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_web_push_subscriptions");

                    b.HasIndex("Endpoint")
                        .IsUnique()
                        .HasDatabaseName("ux_web_push_subscriptions_endpoint");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_web_push_subscriptions_user_id");

                    b.ToTable("web_push_subscriptions", "wonjin");
                });

            modelBuilder.Entity("WonjinApi.Models.RefreshToken", b =>
                {
                    b.HasOne("WonjinApi.Models.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_tokens_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WonjinApi.Models.Reservation", b =>
                {
                    b.HasOne("WonjinApi.Models.Consultant", "Consultant")
                        .WithMany("Reservations")
                        .HasForeignKey("ConsultantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_reservations_consultants_consultant_id");

                    b.HasOne("WonjinApi.Models.User", "DeletedByUser")
                        .WithMany()
                        .HasForeignKey("DeletedByUserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_reservations_users_deleted_by_user_id");

                    b.Navigation("Consultant");

                    b.Navigation("DeletedByUser");
                });

            modelBuilder.Entity("WonjinApi.Models.ReservationLog", b =>
                {
                    b.HasOne("WonjinApi.Models.Reservation", "Reservation")
                        .WithMany("Logs")
                        .HasForeignKey("ReservationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_reservation_logs_reservations_reservation_id");

                    b.Navigation("Reservation");
                });

            modelBuilder.Entity("WonjinApi.Models.ReservationNote", b =>
                {
                    b.HasOne("WonjinApi.Models.User", "AuthorUser")
                        .WithMany()
                        .HasForeignKey("AuthorUserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_reservation_notes_users_author_user_id");

                    b.HasOne("WonjinApi.Models.Reservation", "Reservation")
                        .WithMany("Notes")
                        .HasForeignKey("ReservationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_reservation_notes_reservations_reservation_id");

                    b.Navigation("AuthorUser");

                    b.Navigation("Reservation");
                });

            modelBuilder.Entity("WonjinApi.Models.ReservationNoteRevision", b =>
                {
                    b.HasOne("WonjinApi.Models.User", null)
                        .WithMany()
                        .HasForeignKey("EditedByUserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_reservation_note_revisions_users_edited_by_user_id");

                    b.HasOne("WonjinApi.Models.ReservationNote", "ReservationNote")
                        .WithMany("Revisions")
                        .HasForeignKey("ReservationNoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_reservation_note_revisions_reservation_notes_reservation_no");

                    b.Navigation("ReservationNote");
                });

            modelBuilder.Entity("WonjinApi.Models.ReservationProcedure", b =>
                {
                    b.HasOne("WonjinApi.Models.Procedure", "Procedure")
                        .WithMany("ReservationProcedures")
                        .HasForeignKey("ProcedureId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_reservation_procedures_procedures_procedure_id");

                    b.HasOne("WonjinApi.Models.Reservation", "Reservation")
                        .WithMany("ReservationProcedures")
                        .HasForeignKey("ReservationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_reservation_procedures_reservations_reservation_id");

                    b.Navigation("Procedure");

                    b.Navigation("Reservation");
                });

            modelBuilder.Entity("WonjinApi.Models.WebPushSubscription", b =>
                {
                    b.HasOne("WonjinApi.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_web_push_subscriptions_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WonjinApi.Models.Consultant", b =>
                {
                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("WonjinApi.Models.Procedure", b =>
                {
                    b.Navigation("ReservationProcedures");
                });

            modelBuilder.Entity("WonjinApi.Models.Reservation", b =>
                {
                    b.Navigation("Logs");

                    b.Navigation("Notes");

                    b.Navigation("ReservationProcedures");
                });

            modelBuilder.Entity("WonjinApi.Models.ReservationNote", b =>
                {
                    b.Navigation("Revisions");
                });

            modelBuilder.Entity("WonjinApi.Models.User", b =>
                {
                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
